name: report
version: 0.1.0.0
synopsis: My Haskell report project
description: See report.pdf
maintainer: My Name <my.email@example.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base >= 4.14 && < 5
  - random
  - QuickCheck

library:
  source-dirs: lib


